In [ ]:
import numpy as np
import pandas as pd
%cd /Users/kevjangs/Desktop/cs-ai-quant/cs-ai-quant-roadmap/week01/titanic_forecast
%load_ext autoreload


[Errno 2] No such file or directory: '/Users/kevjangs/Desktop/cs-ai-quant/cs-ai-quant-roadmap/week01/titanic_forecast'
/Users/kevjangs/Desktop/cs-ai-quant/ca-ai-quant-roadmap/week01/titanic_forecast
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
%autoreload 2

test = pd.read_csv('data/test.csv')
train = pd.read_csv('data/train.csv')

In [16]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S


In [15]:
#baseline model Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

X = pd.get_dummies(train[features],dtype=int)
Y = train['Survived']

X_train , X_valid , Y_train , Y_valid = train_test_split(X,Y, test_size=0.2, random_state=62)

model = RandomForestClassifier(n_estimators=100, random_state=62)
model.fit(X_train, Y_train)
valid_preds = model.predict(X_valid)
valid_acc = accuracy_score(Y_valid, valid_preds)

print(f"valid_acc is {valid_acc}")

X_test = pd.get_dummies(test[features],dtype=int)
test_preds = model.predict(X_test)
baseline_submission =pd.DataFrame({'passengerId':test['PassengerId'], 'Survived':test_preds})
baseline_submission.to_csv("data/baseline_submission.csv", index=False)
baseline_submission.head()


valid_acc is 0.8156424581005587


,passengerId,Survived
0,892,0
1,893,0
2,894,0
3,895,0
4,896,1


In [10]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']
for col in train[features].columns:
    print(f"feature is {col}")
    print(col, train[col].isnull().sum())
    print(train[col].unique())


feature is Pclass
Pclass 0
[3 1 2]
feature is Sex
Sex 0
<StringArray>
['male', 'female']
Length: 2, dtype: str
feature is Age
Age 177
[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]
feature is SibSp
SibSp 0
[1 0 3 4 2 5 8]
feature is Parch
Parch 0
[0 1 2 5 3 4 6]
feature is Fare
Fare 0
[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55    31.275    7.8542  16.      29.125
  13.      18.       7.225   26.       8.0292  35.5     31.3875 263.
   7.8792   7.8958 